'use strict';
module.exports.directoryCategories = [{
    name: 'Others',
    _subCategories: [{
        name: 'Dealers',
    }, {
        name: 'Finance',
    }, {
        name: 'Manufacturers',
    }, {
        name: 'Transportation of Forklift',
    }, ],
}, {
    name: 'Agent',
    _subCategories: [{
        name: 'Flexi',
    }, {
        name: 'Aisle Master',
    }, ],
}, {
    name: 'Appointed Dealers',
    _subCategories: [{
        name: 'BT',
    }, {
        name: 'Clark',
    }, {
        name: 'Komatsu',
    }, {
        name: 'Mitsubishi',
    }, {
        name: 'Nichiyu',
    }, {
        name: 'Nissan',
    }, {
        name: 'Still',
    }, {
        name: 'TCM',
    }, {
        name: 'Toyota',
    }, {
        name: 'Yale',
    }, ],
}, {
    name: 'Modification',
    _subCategories: [{
        name: 'Explosion Proof',
    }, {
        name: 'Attachment',
    }, ],
}, {
    name: 'Repair',
    _subCategories: [{
        name: 'Mast',
    }, ],
}, {
    name: 'Spare Parts',
    _subCategories: [{
        name: 'Battery',
    }, {
        name: 'Castor',
    }, {
        name: 'General',
    }, {
        name: 'Tyre',
    }, ],
}, ];
module.exports.businesses = [{
    _categories: ['repair|mast', ],
    name: 'Joo Lee Engineering Pte Ltd',
    address: {
        street: '24 Sg Kadut St 3',
        city: 'Singapore',
        country: 'Singapore',
        postal: '729152',
    },
    phone: '62695108',
    fax: '',
    email: 'sales@joolee.net',
}, {
    _categories: ['spare-parts|battery', ],
    name: 'Energy Systems Transnational Pte Ltd.',
    address: {
        street: '69C Tuas South Avenue 1',
        city: 'Singapore',
        country: 'Singapore',
        postal: '637500',
    },
    phone: '98308886',
    fax: '62626936',
    email: 'sales@est-group.net',
}, {
    _categories: ['spare-parts|battery', ],
    name: 'Battery Asia (S) Pte Ltd',
    address: {
        street: 'No.11 Kian Teck Road',
        city: 'Singapore',
        country: 'Singapore',
        postal: '628768',
    },
    phone: '63163661',
    fax: '63163662',
    email: 'sales@batteryasia.com.sg',
}, {
    _categories: ['spare-parts|battery', ],
    name: 'Chloride Batteries S E Asia Pte Ltd',
    address: {
        street: '106 Neythal Road, Jurong Town',
        city: 'Singapore',
        country: 'Singapore',
        postal: '628594',
    },
    phone: '62652444',
    fax: '62651478',
    email: 'salesdesk@cbsea.com.sg',
}, {
    _categories: ['spare-parts|battery', ],
    name: 'Swee Hin Power Systems Pte Ltd',
    address: {
        street: '3, Kian Teck Way',
        city: 'Singapore',
        country: 'Singapore',
        postal: '628732',
    },
    phone: '62616688',
    fax: '62655998',
    email: 'md@sweehin.com.sg',
}, {
    _categories: ['spare-parts|castor', ],
    name: 'Castor & Wheel Singapore Pte Ltd',
    address: {
        street: '29 Kaki Bukit Place',
        city: 'Singapore',
        country: 'Singapore',
        postal: '416207',
    },
    phone: '67456944',
    fax: '67456945',
    email: 'singapore@castorwheel.com',
}, {
    _categories: ['spare-parts|tyre', ],
    name: 'A A Forklift Tyres Pte Ltd',
    address: {
        street: '62 Sg Kadut Drive',
        city: 'Singapore',
        country: 'Singapore',
        postal: '729571',
    },
    phone: '63666661',
    fax: '63681940',
    email: 'sales@aaforklifttyres.com.sg',
}, {
    _categories: ['spare-parts|tyre', ],
    name: 'Aexus Auto Trading Pte Ltd.',
    address: {
        street: '5 Soon Lee Street, #02-43, Pioneer Point',
        city: 'Singapore',
        country: 'Singapore',
        postal: '627607',
    },
    phone: '63689980',
    fax: '63683009',
    email: 'sales@aexus.com.sg',
}, {
    _categories: ['spare-parts|general', ],
    name: 'SUNNFOREST ENTERPRISES',
    address: {
        street: 'Block 735 Pasir Ris West Plaza #01-328',
        city: 'Singapore',
        country: 'Singapore',
        postal: '510735',
    },
    phone: '61000528',
    fax: '67258109',
    email: 'sales@sunnforest.com',
}, {
    _categories: ['spare-parts|general', ],
    name: 'Alltrade Forklift Parts Pte Ltd',
    address: {
        street: 'No.97 Second Lok Yang Road, Jurong',
        city: 'Singapore',
        country: 'Singapore',
        postal: '628170',
    },
    phone: '67442442',
    fax: '67444649',
    email: 'sales@alltrade.com.sg',
}, {
    _categories: ['modification|attachment', ],
    name: 'Sunstream Industries Pte Ltd.',
    address: {
        street: '18 Tuas South Street 5',
        city: 'Singapore',
        country: 'Singapore',
        postal: '637796',
    },
    phone: '6795-7555',
    fax: '6863-1368',
    email: 'enquiry@sunstream-industries.com',
}, {
    // eslint-disable-next-line
    _categories: ['others|dealers', 'spare-parts|general', 'modification|attachment', ],
    name: 'TVH Singapore Pte Ltd',
    address: {
        street: '6, Gul Street 3',
        city: 'Singapore',
        country: 'Singapore',
        postal: '629264',
    },
    phone: '62761450',
    fax: '62761452',
    email: 'sales.singapore@tvh.com',
}, {
    _categories: ['modification|attachment', ],
    name: 'RFA Industries Pte Ltd.',
    address: {
        street: '22 Soon Lee Road',
        city: 'Singapore',
        country: 'Singapore',
        postal: '628082',
    },
    phone: '68623011',
    fax: '68623083',
    email: 'enquiry@rfa-industries.com',
}, {
    _categories: ['modification|explosion-proof', ],
    name: 'Pyroban',
    address: {
        street: '14 Tractor Road',
        city: 'Singapore',
        country: 'Singapore',
        postal: '627973',
    },
    phone: '68287333',
    fax: '',
    email: '',
}, {
    _categories: ['', ],
    name: 'Springwell Marketing Services Pte Ltd',
    address: {
        street: 'No.50 Tuas Avenue 11, #03-37 Tuas Lot',
        city: 'Singapore',
        country: 'Singapore',
        postal: '639107',
    },
    phone: '64830319',
    fax: '64830917',
    email: 'springwell@singnet.com.sg',
}, {
    _categories: ['others|dealers', ],
    name: 'GAMBIT ENGINEERING & FORKLIFT SERVICES',
    address: {
        street: '25 Tuas Ave 3',
        city: 'Singapore',
        country: 'Singapore',
        postal: '639418',
    },
    phone: '68982128',
    fax: '',
    email: '',
}, {
    _categories: ['others|dealers', ],
    name: 'Mashgate Pte Ltd',
    address: {
        street: '38 Woodlands Industrial Park E1 #07-19',
        city: 'Singapore',
        country: 'Singapore',
        postal: '757700',
    },
    phone: '63142550',
    fax: '',
    email: 'info@mashgate.com',
}, {
    _categories: ['others|dealers', ],
    name: 'Red Forklifts Repairers',
    address: {
        street: '22 Sungei Kadut Way',
        city: 'Singapore',
        country: 'Singapore',
        postal: '728777',
    },
    phone: '63664173',
    fax: '',
    email: '',
}, {
    _categories: ['others|dealers', ],
    name: 'Hock Eek Seng Machinery Pte Ltd',
    address: {
        street: '2 Sg Kadut Dr Kranji Ind Est',
        city: 'Singapore',
        country: 'Singapore',
        postal: '729553',
    },
    phone: '63688002',
    fax: '63688001',
    email: '',
}, {
    _categories: ['others|dealers', ],
    name: 'Cosmopolitan Engineering Services Pte Ltd',
    address: {
        street: '4 Loyang Walk',
        city: 'Singapore',
        country: 'Singapore',
        postal: '508787',
    },
    phone: '65467728',
    fax: '65467729',
    email: 'coslease@cosmopolitan.com.sg',
}, {
    _categories: ['others|dealers', ],
    name: 'Dynasty Lift Trucks Services Pte Ltd',
    address: {
        street: '92 Tagore Lane',
        city: 'Singapore',
        country: 'Singapore',
        postal: '787534',
    },
    phone: '65561860',
    fax: '65561850',
    email: ' sales@dynastyforklift.com',
}, {
    _categories: ['others|dealers', ],
    name: 'Liden Lift Trucks Services Pte Ltd.',
    address: {
        street: '4 Penjuru Place #01-21 Penjuru Tech Hub',
        city: 'Singapore',
        country: 'Singapore',
        postal: '608782',
    },
    phone: '62652208',
    fax: '62652205',
    email: 'enquiry@liden.com.sg',
}, {
    _categories: ['others|dealers', ],
    name: 'Aver Asia (S) Pte Ltd',
    address: {
        street: 'Aver Asia (S) Pte Ltd',
        city: 'Singapore',
        country: 'Singapore',
        postal: '629953',
    },
    phone: '68616368',
    fax: '68612142',
    email: 'enquiry@averasia.com',
}, {
    _categories: ['others|dealers', ],
    name: 'KOH M.H.E Pte Ltd',
    address: {
        street: '280 Woodlands Industrial Park E5 #01-12 Harvest @ Woodlands',
        city: 'Singapore',
        country: 'Singapore',
        postal: '757322',
    },
    phone: '69969339',
    fax: '',
    email: 'sales@kmhe.com.sg',
}, {
    _categories: ['others|dealers', ],
    name: 'Passion Lift Trucks Services',
    address: {
        street: '11 Yishun Industrial St1 #01-110 North Spring Bizhub',
        city: 'Singapore',
        country: 'Singapore',
        postal: '768089',
    },
    phone: '62431239',
    fax: '66595781',
    email: 'brina@passionlts.com.sg',
}, {
    _categories: ['others|dealers', ],
    name: 'Union Forklift Pte Ltd',
    address: {
        street: 'No 29, Kranji Link',
        city: 'Singapore',
        country: 'Singapore',
        postal: '728667',
    },
    phone: '63622587',
    fax: '63653293',
    email: 'union@forklifts.com.sg',
}, {
    _categories: ['others|dealers', ],
    name: 'Beng Siang Machinery Pte Ltd',
    address: {
        street: '67J Tuas South Ave 1',
        city: 'Singapore',
        country: 'Singapore',
        postal: '637588',
    },
    phone: '63635561',
    fax: '63635562',
    email: 'enquiry@bsforklift.com.sg',
}, {
    _categories: ['others|dealers', ],
    name: 'Soh Kim Seng Engineering & Trading Pte Ltd',
    address: {
        street: '245 Jalan Ahmad Ibrahim',
        city: 'Singapore',
        country: 'Singapore',
        postal: '629144     ',
    },
    phone: '6897-7060',
    fax: '6897-7059',
    email: 'general@skset.com',
}, {
    _categories: ['others|dealers', ],
    name: 'Fork & Lift (S) Pte Ltd',
    address: {
        street: '190 Woodlands Industrial Park E5 #06-04',
        city: 'Singapore',
        country: 'Singapore',
        postal: '757516',
    },
    phone: '91813091',
    fax: '',
    email: '',
}, {
    _categories: ['others|dealers', ],
    name: 'Merah Engineering Pte Ltd',
    address: {
        street: '48 Toh Guan Road East, #04-120, Enterprise Hub',
        city: 'Singapore',
        country: 'Singapore',
        postal: '608586',
    },
    phone: '65616630',
    fax: '65616631',
    email: 'mgr@merah-engineering.com',
}, {
    _categories: ['others|dealers', ],
    name: 'Aexus Auto Trading Pte Ltd.',
    address: {
        street: '5 Soon Lee Street, #02-43, Pioneer Point',
        city: 'Singapore',
        country: 'Singapore',
        postal: '627607',
    },
    phone: '63689980',
    fax: '63683009',
    email: 'sales@aexus.com.sg',
}, {
    _categories: ['others|dealers', ],
    name: 'Dowell Heavy Equipment',
    address: {
        street: '#12-56, 524 Serangoon North Ave 4',
        city: 'Singapore',
        country: 'Singapore',
        postal: '550524',
    },
    phone: '98892387',
    fax: '',
    email: 'enquiry.dowell@gmail.com',
}, {
    _categories: ['others|dealers', ],
    name: 'Lifty Tech Pte Ltd',
    address: {
        street: '10 Anson Road #10-11 International Plaza',
        city: 'Singapore',
        country: 'Singapore',
        postal: '079903',
    },
    phone: '31514828',
    fax: '',
    email: '',
}, {
    _categories: ['others|dealers', ],
    name: 'Sunnforest Enterprises',
    address: {
        street: 'Block 735 Pasir Ris West Plaza #01-328',
        city: 'Singapore',
        country: 'Singapore',
        postal: '510735',
    },
    phone: '61000528',
    fax: '67258109',
    email: 'sales@sunnforest.com',
}, {
    _categories: ['others|dealers', ],
    name: 'Eastman Lift Trucks Pte Ltd',
    address: {
        street: '9 Tuas South Street 8',
        city: 'Singapore',
        country: 'Singapore',
        postal: '636931',
    },
    phone: '68619860',
    fax: '68621969',
    email: 'sales@eastman.com.sg',
}, {
    _categories: ['others|dealers', ],
    name: 'Singapore Forklifts',
    address: {
        street: '22 Woodlands Link #03-27',
        city: 'Singapore',
        country: 'Singapore',
        postal: '738734',
    },
    phone: '91255088',
    fax: '',
    email: 'sales@singaporeforklifts.com',
}, {
    _categories: ['agent|flexi', ],
    name: 'Tysen Technologies Pte Ltd (Main Office)',
    address: {
        street: '21 Bukit Batok Crescent #18-80 Wcega Tower',
        city: 'Singapore',
        country: 'Singapore',
        postal: '658065',
    },
    phone: '66593682',
    fax: '66593683',
    email: 'info@tysentech.com',
}, {
    _categories: ['agent|flexi', ],
    name: 'Tysen Technologies Pte Ltd (Warehouse and Workshop)',
    address: {
        street: '152 Tuas South Avenue 2',
        city: 'Singapore',
        country: 'Singapore',
        postal: '637181',
    },
    phone: '66593682',
    fax: '66593683',
    email: 'info@tysentech.com',
}, {
    _categories: ['agent|aisle-master', ],
    name: 'Paves Asia Pacific Pte Ltd',
    address: {
        street: '21, Bukit Batok Crescent #16-83 WCEGA Tower',
        city: 'Singapore',
        country: 'Singapore',
        postal: '650865',
    },
    phone: '65708091',
    fax: '65708092',
    email: 'sales@paves.com.sg',
}, {
    _categories: ['others|manufacturers', ],
    name: 'Hyster Singapore Pte Ltd',
    address: {
        street: '47 Joo Koon Circle',
        city: 'Singapore',
        country: 'Singapore',
        postal: '629067',
    },
    phone: '68633387',
    fax: '68633349',
    email: '',
}, {
    _categories: ['others|manufacturers', ],
    name: 'Linde Material Handling Asia Pacific Pte Ltd',
    address: {
        street: '5 Loyang Way',
        city: 'Singapore',
        country: 'Singapore',
        postal: '508720',
    },
    phone: '65453488',
    fax: '65450627',
    email: 'info@lindemh.com.sg',
}, {
    _categories: ['others|manufacturers', ],
    name: 'Jungheinrich Lift Truck Singapore',
    address: {
        street: '7 Joo Koon Way',
        city: 'Singapore',
        country: 'Singapore',
        postal: '628945',
    },
    phone: '65587600',
    fax: '65587611',
    email: 'info@jungheinrich.com.sg',
}, {
    _categories: ['others|manufacturers', ],
    name: 'Mitsubishi Nichiyu Forklift Asia Pacific Pte Ltd.',
    address: {
        street: 'No.1 Tuas West Street',
        city: 'Singapore',
        country: 'Singapore',
        postal: '637444',
    },
    phone: '65716237',
    fax: '68977562(Office) /68977563(Warehouse)',
    email: 'inquiry@mna.sg',
}, {
    _categories: ['others|manufacturers', ],
    name: 'Komatsu Seisakusho Co. Ltd',
    address: {
        street: '25 Tagore Lane #04-09 (Room2),Singapore Godown',
        city: 'Singapore',
        country: 'Singapore',
        postal: '787602',
    },
    phone: '63887624',
    fax: '63887625',
    email: 'sales@komatsufilter.co.jp',
}, {
    _categories: ['others|manufacturers', ],
    name: 'Manitou Asia Pte Ltd',
    address: {
        street: '57 Tuas South Avenue 1',
        city: 'Singapore',
        country: 'Singapore',
        postal: '637327',
    },
    phone: '68620771',
    fax: '68620216',
    email: 'info@manitouasia.com',
}, {
    _categories: ['others|manufacturers', ],
    name: 'Crown Singapore',
    address: {
        street: '15 Tuas Ave 8',
        city: 'Singapore',
        country: 'Singapore',
        postal: '639230',
    },
    phone: '68613669',
    fax: '68610175',
    email: 'contact.singapore@crown.com',
}, {
    _categories: ['others|manufacturers', ],
    name: 'Pramac Asia Pte Ltd',
    address: {
        street: '10 Bukit Batok Crescent #11-08 The Spire',
        city: 'Singapore',
        country: 'Singapore',
        postal: '658079',
    },
    phone: '65587888',
    fax: '65587878',
    email: 'info.sg@pramac.com',
}, {
    _categories: ['others|manufacturers', ],
    name: 'MHE-Demag (S) Pte Ltd',
    address: {
        street: '33 Gul Circle',
        city: 'Singapore',
        country: 'Singapore',
        postal: '629570',
    },
    phone: '63053500',
    fax: '68621933',
    email: 'info_mhe@mhe-demag.com',
}, {
    _categories: ['others|transportation-of-forklift', ],
    name: 'Kim Soon Lee',
    address: {
        street: '200 Bedok South Ave 1',
        city: 'Singapore',
        country: 'Singapore',
        postal: '469331',
    },
    phone: '67412222',
    fax: '67417692(Ops) /67498426 (Admin)',
    email: 'enquiry@kimsoonlee.com',
}, {
    _categories: ['others|transportation-of-forklift', ],
    name: 'Transgrow Logistics Pte Ltd',
    address: {
        street: '5 Soon Lee Street, #02-23 Pioneer Point',
        city: 'Singapore',
        country: 'Singapore',
        postal: '627607',
    },
    phone: '97909659',
    fax: '',
    email: 'joey.yee@transgrow.com.sg',
}, {
    _categories: ['others|transportation-of-forklift', ],
    name: 'Tat Seng Machine Movers Pte Ltd',
    address: {
        street: '14 Defu Lane 9',
        city: 'Singapore',
        country: 'Singapore',
        postal: '539255',
    },
    phone: '62870892 /96639088',
    fax: '62839288',
    email: 'tatseng@machinemovers.com.sg',
}, {
    _categories: ['others|transportation-of-forklift', ],
    name: 'Poh Tiong Choon Logistics Limited',
    address: {
        street: '48 Pandan Road',
        city: 'Singapore',
        country: 'Singapore',
        postal: '609289',
    },
    phone: '62682522',
    fax: '62643394',
    email: 'sales@ptclogistics.com.sg',
}, {
    _categories: ['others|transportation-of-forklift', ],
    name: 'HL Group of Companies',
    address: {
        street: '16-18A Jalan Tukang',
        city: 'Singapore',
        country: 'Singapore',
        postal: '619256',
    },
    phone: '62652002',
    fax: '67796116',
    email: 'sales@hlgroup.com.sg',
}, {
    _categories: ['appointed-dealers|komatsu', ],
    name: 'Scantruck Engineering Pte Ltd.',
    address: {
        street: '5 Tuas Avenue 10',
        city: 'Singapore',
        country: 'Singapore',
        postal: '639129',
    },
    phone: '63056600',
    fax: '68610210',
    email: 'info@scantruck.com.sg',
}, {
    _categories: ['appointed-dealers|toyota', 'appointed-dealers|bt', ],
    name: 'UMW Equipment & Engineering Pte Ltd',
    address: {
        street: '108 International Road',
        city: 'Singapore',
        country: 'Singapore',
        postal: '629173',
    },
    phone: '62653155',
    fax: '62658494',
    email: 'sales@umweepl.com.sg',
}, {
    _categories: ['appointed-dealers|tcm', ],
    name: 'Hock Eek Seng Machinery Pte Ltd',
    address: {
        street: '2 Sungei Kadut Drive',
        city: 'Singapore',
        country: 'Singapore',
        postal: '729553',
    },
    phone: '63688002',
    fax: '63688001',
    email: 'enquiry@hockes.com.sg',
}, {
    _categories: ['appointed-dealers|nissan', ],
    name: 'Tan Chong Industrial Machinery Pte Ltd',
    address: {
        street: '23 Jalan Buroh',
        city: 'Singapore',
        country: 'Singapore',
        postal: '619479',
    },
    phone: '62653666',
    fax: '62641666',
    email: '',
}, {
    // eslint-disable-next-line
    _categories: ['appointed-dealers|still', 'appointed-dealers|mitsubishi', 'appointed-dealers|nichiyu', ],
    name: 'Goldbell Engineering Pte Ltd',
    address: {
        street: '10 Tuas Ave 18',
        city: 'Singapore',
        country: 'Singapore',
        postal: '638894',
    },
    phone: '68610007',
    fax: '68613676',
    email: '',
}, {
    _categories: ['appointed-dealers|yale', ],
    name: 'Y K Toh Marketing Pte Ltd',
    address: {
        street: '8, Changi North Street1, TSK Building,',
        city: 'Singapore',
        country: 'Singapore',
        postal: '498829',
    },
    phone: '65423232',
    fax: '65423636',
    email: 'enquiry@yktoh.com',
}, {
    _categories: ['appointed-dealers|clark', ],
    name: 'Multico Equipment and Parts Pte Ltd',
    address: {
        street: '11 Tuas View Crescent, Multico Building',
        city: 'Singapore',
        country: 'Singapore',
        postal: '637643',
    },
    phone: '68632863',
    fax: '68636817',
    email: 'jason@mep.multicoasia.com',
}, {
    _categories: ['others|finance', ],
    name: 'Hitachi Capital Asia Pacific Pte Ltd',
    address: {
        street: '111 Somerset Road #11-05 TripleOne Somerset',
        city: 'Singapore',
        country: 'Singapore',
        postal: '238164',
    },
    phone: '67341222',
    fax: '67348685',
    email: '',
}, {
    _categories: ['others|finance', ],
    name: 'UOB Commercial Banking - Machinery and Equipment Financing',
    address: {
        street: '80 Raffles Place, UOB Plaza',
        city: 'Singapore',
        country: 'Singapore',
        postal: '048624',
    },
    phone: '62266121',
    fax: '',
    email: '',
}, {
    _categories: ['others|finance', ],
    name: 'Singapura Finance',
    address: {
        street: '150 Cecil Street #01-00',
        city: 'Singapore',
        country: 'Singapore',
        postal: '069543',
    },
    phone: '68800688',
    fax: '',
    email: '',
}, {
    _categories: ['others|finance', ],
    name: 'Swee Seng Credit Pte Ltd',
    address: {
        street: '21 Toh Guan Road East #01-01/02 Toh Guan Centre',
        city: 'Singapore',
        country: 'Singapore',
        postal: '608609',
    },
    phone: '66536116',
    fax: '64633808',
    email: 'credit@ssgroup.sg',
}, {
    _categories: ['others|finance', ],
    name: 'DBS SME Banking - Equipment Financing',
    address: {
        // eslint-disable-next-line
        street: '12 Marina Boulevard, Level 3, Marina Bay Financial Centre Tower 3',
        city: 'Singapore',
        country: 'Singapore',
        postal: '018982',
    },
    phone: '18002222200',
    fax: '',
    email: '',
}, {
    _categories: ['others|finance', ],
    name: 'Hong Leong Finance',
    address: {
        street: '16 Raffles Quay, #01-05, Hong Leong Building',
        city: 'Singapore',
        country: 'Singapore',
        postal: '048581',
    },
    phone: '65796738',
    fax: '63233271',
    email: '',
}, {
    _categories: ['others|finance', ],
    name: 'ORIX Leasing Singapore Limited',
    address: {
        street: '331 North Bridge Road #19-01/06 Odeon Towers',
        city: 'Singapore',
        country: 'Singapore',
        postal: '188720',
    },
    phone: '63393622',
    fax: '63393966',
    email: 'loanenquiries@ols.com.sg',
}, ];